version: '3.1'

services:
  postgres:
    image: postgres:11.5
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin

volumes:
  postgres:
